WIP: trying out image build

diff --git a/.github/actions/build-and-push-to-quay/action.yml b/.github/actions/build-and-push-to-quay/action.yml
--- a/.github/actions/build-and-push-to-quay/action.yml
+++ b/.github/actions/build-and-push-to-quay/action.yml
@@ -30,6 +30,10 @@ inputs:
     description: "Should we tag with 'latest'?"
     required: false
     default: false
+  tag_cargo_version_if_present:
+    description: "Should we tag with the version found in Cargo.toml, if found?"
+    required: false
+    default: false
   tags:
     description: "Whitespace-separated tags, not including the registry, for example 'v1' or 'v1 release-1.0'. There are also some default tags provided, please see the other options of this action."
     required: false
@@ -38,14 +42,39 @@ outputs: {}
 runs:
   using: "composite"
   steps:
+    - name: Install TOML parser
+      shell: bash
+      run: |
+       set -xe
+       wget https://github.com/freshautomations/stoml/releases/download/v0.7.1/stoml_linux_amd64
+       mv stoml_linux_amd64 stoml
+       chmod +x stoml
+       sudo mv stoml /usr/local/bin/
     - name: Create whitespace-separated tags list
       shell: bash
       id: tags
       run: |
-        set -xe
+        set -e
 
         # input tags
         TAGS='${{ inputs.tags }}'
+
+        cd ${{ inputs.docker_directory }}
+
+        if [ "${{ inputs.tag_cargo_version_if_present }}" == "true" ] && [ test -f "Cargo.toml" ]; then
+            echo "Cargo file detected, adding to tags"
+            VERSION=$(stoml Cargo.toml package.version)
+            TAGS="$TAGS $VERSION"
+        fi
+
+        # # Fail if any of these tags are already published
+        # IFS=' ' read -ra TAG_ARRAY <<< "${TAGS}"
+        # for tag in "${TAG_ARRAY[@]}"; do
+        #   if docker manifest inspect ${{ inputs.registry }}/${{ inputs.image_name }}:$tag > /dev/null; then
+        #     echo "Error: found this is already published to Quay ${{ inputs.registry }}/${{ inputs.image_name }}:$tag"
+        #     exit 1
+        #   fi
+        # done
 
         # Calendar version
         if [ "${{ inputs.publish_calver }}" == "true" ]; then
