don't fail helm test for new charts

diff --git a/.github/workflows/helm-test.yaml b/.github/workflows/helm-test.yaml
--- a/.github/workflows/helm-test.yaml
+++ b/.github/workflows/helm-test.yaml
@@ -52,15 +52,22 @@ jobs:
 
       - name: Check chart version
         run: |
+      - name: Check chart version
+        run: |
           cd code
           CURR_VERSION=$(cat ${{ matrix.path }}/Chart.yaml | grep version: | cut -d ' ' -f 2)
-          MAIN_VERSION=$(git show main:${{ matrix.path }}/Chart.yaml | grep version: | cut -d ' ' -f 2)
+          MAIN_VERSION=$(git show main:${{ matrix.path }}/Chart.yaml 2>/dev/null | grep version: | cut -d ' ' -f 2 || echo "")
 
           echo -n "Current version: ${CURR_VERSION}\n"
           echo -n "Previous version: ${MAIN_VERSION}\n"
 
+          if [ -z "$MAIN_VERSION" ]; then
+            echo "Chart not found in the main branch. Continuing..."
+            exit 0
+          fi
+
           if [ "$CURR_VERSION" = "$MAIN_VERSION" ]; then
-            echo "Helm chart  ${{ matrix.path }} version is unchanged and needs to be bumped!"
+            echo "Helm chart ${{ matrix.path }} version is unchanged and needs to be bumped!"
             exit 1
           fi
 
